image:
  file: .gitpod.Dockerfile
  
tasks:
  - init: |
      python -m venv venv
      source venv/bin/activate
      pip install --upgrade pip wheel setuptools
      pip install -r requirements.txt
  - command: |
      source venv/bin/activate
      Rscript requirements.R
  
vscode:
  extensions:
    - ms-toolsai.jupyter
    - ms-python.python
    - Ikuyadeu.r
    - reditorsupport.r-lsp
    - vscode-icons-team.vscode-icons
    - ritwickdey.liveserver
    - james-yu.latex-workshop
    - dracula-theme.theme-dracula
    - enkia.tokyo-night
    - ritwickdey.LiveServer
